version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres-db
    environment:
      POSTGRES_DB: devops_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Tino1372
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: devops-app
    depends_on:
      - postgres
    ports:
      - "8080:8080"