name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
            distribution: 'temurin'
            java-version: '21'

      - name: Grant execute permission for gradlew   #added to grant permission
        run: chmod +x gradlew

      - name: Build project
        run: ./gradlew build -x test

      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image with compose
        run: docker compose build   # This builds the services defined in your docker-compose.yml


      - name: Tag and Push Docker image
        run: |
          docker tag devops-kotlin-app:latest ${{ secrets.DOCKER_USERNAME }}/devops-kotlin-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/devops-kotlin-app:latest